apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/kataria/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/kataria/.minikube/client.crt
    client-key: /home/kataria/.minikube/client.key
