apiVersion: v1
clusters:
- cluster:
    certificate-authority: <ca-cert>
    server: <server-ip>
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: <client-cert> 
    client-key: <client-key>
